### ISSUE TITLE
Recurring jobs for every second

### ISSUE THREAD

**Issue by mspraneeth98** [jobrunr/jobrunr#105]
The minimum interval for recurring jobs is one minute currently. It will be great if we can decrease it further to one second.

**Comment by rdehuyss** [comment]
I don't think this will ever possible using JobRunr as the load on the storage provider would increase a lot (necessary because of optimistic locking).

I am wondering what your business use case is to have a recurring job every second?

**Comment by mspraneeth98** [comment]
Live stream some data in background

**Comment by mspraneeth98** [comment]
Can you explain why would this increase the load on the storage provider? My requirement is a single recurring job executing a method for every second

**Comment by rdehuyss** [comment]
Well, the life cycle of a recurring job is as follows:
- every 15 seconds the `BackgroundJobServer` checks if there are new recurring jobs to execute
- if there is one to execute, it schedules the job to be executed at the correct time (which is a state change and saved to the database)
- from scheduled, the job goes to enqueued (which is a state change and saved to the database).
- as there may be many (more than 10) `BackgroundjobServer`s trying to execute all enqueued jobs, these all would need to check the `StorageProvider` each second where as they now do it only every 15 seconds.
- as soon as a `BackgroundjobServer` is idle, it starts processing enqueued jobs and changes the state to 'Processing' (which is a state change and also saved to the database). This is done because otherwise multiple `BackgroundjobServer`s would execute the same job around the same time, which is something you typically don't want.
- As soon as the job is finished, it is again a state change and saved to the database again.

So, each recurring job results in at least 6 database calls. It _may_ be possible of you only have BackgroundJobServer (and what if your recurring job takes more than 1 second?) but JobRunr is meant for distributed jobs. 

Also in the dashboard, the amount of jobs would be so high that it wouldn't add any benefit anymore as it would be too hard to find a job (as there are then at 86400 jobs / day).

I think that **JobRunr is not the good tool for the problem you have at hand**. To live stream some data in the background, I would just create a simple service that keeps running (e.g. in a while loop or using async methods to check if there is new data to be streamed)

**Comment by mspraneeth98** [comment]
Thanks for the explanation. I think you misunderstood my case. I don't want a new job every second, I want a few parallel jobs to execute the same method every second with different arguments.

But anyway, the problem is solved by changing the polling interval of the BackgroundJobServer to 1 second.

Thanks again!

**Comment by rdehuyss** [comment]
I'm happy that your problem is solved.

Do note that you are now putting a higher load on your StorageProvider and I would monitor it to see if it can cope with the load..
