### ISSUE TITLE
[BUG]job state count is Inconsistent

### ISSUE THREAD

**Issue by hxbb00** [jobrunr/jobrunr#20]
**Describe the bug**
when the SUCCEEDED job is DELETED, table **jobrunr_jobs** update the **state** column to DELETED,but table **jobrunr_job_counters** is not update the **amount** colum

**Environment**
I'm using version 0.9.7
I'm running on JRE / JDK 1.8

**Additional context**
![image](https://user-images.githubusercontent.com/14104435/84125940-d92e3f80-aa6f-11ea-9c4c-23ec48a95cda.png)

![image](https://user-images.githubusercontent.com/14104435/84125844-bac84400-aa6f-11ea-96e5-d66b5ce0b2a3.png)

**Comment by hxbb00** [comment]
job State has not record DELETED

**Comment by rdehuyss** [comment]
This is expected behavior and Dashboard related. See also the screenshot...

In the dashboard you see the amount of scheduled, enqueued, processing, failed and succeeded jobs (the counters). I don't see an advantage of having also a counter for all the deleted items.

![counters](https://user-images.githubusercontent.com/567842/84167638-c9fec000-aa76-11ea-9d96-7471fb5ee769.png)
