### ISSUE TITLE
[Feature] Make DB polling check as supressable warning instead of hard restriction

### ISSUE THREAD

**Issue by Ragin-LundF** [jobrunr/jobrunr#256]
**Is your feature request related to a problem? Please describe.**
We have some small modules, which are using JobRunr for some tasks.
Since version 4 the `pollingInterval` changed to a minimum of 5 seconds (https://github.com/jobrunr/jobrunr/blob/e233afcf55dffa9dff7654f2db9c961ed17dffb3/core/src/main/java/org/jobrunr/server/BackgroundJobServerConfiguration.java#L42).

**Describe the solution you'd like**
It should not be restricted hard by the system to set the polling to 1s.
To give users a hint, this should be a supressable warning, but no stopper.

**Describe alternatives you've considered**
If this is not possible, how can we change it without creating an own fork?

**Comment by benallard** [comment]
For test  scenarios using an in-memory database, we'd like to be able to set it to a small value as well.

**Comment by Ragin-LundF** [comment]
It is still an issue...
Also others have reported the same point:

https://github.com/jobrunr/jobrunr/issues/260

**Comment by rdehuyss** [comment]
To be honest, I really don't feel like changing this. The amount of issues this resulted in was just too many.

People all just put this on 1 sec and then complain that there database is acting slow, ...

Since I'm doing all the support alone, I don't have the time to follow up on all of this. Sorry.

**Comment by rdehuyss** [comment]
I understand your point of view but not everybody is running Postgres. The real solution in my eyes for this problem is #88. 
Also, JobRunr was never meant to be high precision but rather for long-running jobs.

Currently, I'm doing too much unpaid JobRunr support in my free time for things that are out of my hands and do take a lot of time to investigate (e.g. see some recently opened issues for JobRunr related to MySql).
