### ISSUE TITLE
[Feature] R2dbc support

### ISSUE THREAD

**Issue by polyoxidonium** [jobrunr/jobrunr#257]
On the project we are trying to implement housekeeping for the database and I would jobrunr as a pretty nice tool, however,
we are using r2dbc drivers (h2 and mssql) 

I am not sure if there is actually a possibility but it would be fine if either of the next 2 solutions would be applied.

1. Solution (the ideal one)

Add support for r2dbc drivers so the jobrunr can manage jobs in a reactive way. 

2. Solution

Add support to provide existing connection at least via jdbc driver. 
This would altough mean that jobrunr would not manage sql connection and corresponding statements in a reactive way.
Im not sure this is actually doable via DataSource bean. 
I'd rather expect to provide datasource url, username, password and so on.

**Comment by rdehuyss** [comment]
Solution 2 works out of the box. JobRunr is not managing SQL connections, that's the responsibility of the DataSource bean.

See https://www.jobrunr.io/en/documentation/configuration/fluent/.

**Comment by polyoxidonium** [comment]
> Solution 2 works out of the box. JobRunr is not managing SQL connections, that's the responsibility of the DataSource bean.
> 
> See https://www.jobrunr.io/en/documentation/configuration/fluent/.

The issue is that Jobrunr expect Datasource bean which is not supported by spring r2dbc. 
It has its own factory methods, see:
https://github.com/spring-projects/spring-data-r2dbc/issues/40

Thats why i would expect a way to define the sqlprovider not by providing Datasource bean but lets say some configuration properties like url, password and name... 
something like Flyway supports.
We se flyway to initialize db via jdbc driver and then in application later we use spring r2dbc

**Comment by rdehuyss** [comment]
In this point in time, I will not add a reactive client. You can just create an extra DataSource, next to spring r2dbc and pass that to JobRunr. The coding impact is minimal.

Reason that I do not want to add support for R2dbc is that Project Loom is around the corner which makes this obsolete in my eyes.

**Comment by feribg** [comment]
+1 on this one, solution 2 doesn't really work, any integration of jobrnr in a non blocking codebase is immediately met with 2 ugly hacks:
* jdbc dependency
* introduce a threadpool just to run `.enqueue` because contrary to it's contract `Creates a new fire-and-forget job based on a given lambda.` it's not fire and forget it's fire->block->hope there's a connection.

So if we assume that loom is not going to be a wide spread thing 3-4 years time and more and more frameworks are going the non blocking http route (it does make some sense), then at least a `completableFuture` enqueue will allow us to write our own non blocking driver which should be trivial. It will probably unlock a lot nicer implementation of existing non-blocking first drivers that are forced to block.

**Comment by hantsy** [comment]
> Solution 2 works out of the box. JobRunr is not managing SQL connections, that's the responsibility of the DataSource bean.
> 
> See https://www.jobrunr.io/en/documentation/configuration/fluent/.

R2dc does not use DataSource to connect db, it is a different protocol for the ReactiveStreams world.

**Comment by rdehuyss** [comment]
Well, as long as no Enterprise customer has this as a requirement AND wants to pay for the development or somebody from the community adds support for this, I'm afraid I won't add it.

Again, Loom is already in Java 20 and will also be supported in Java 21 which is LTS. 

See also this great thread on Reddit: https://www.reddit.com/r/java/comments/1159e6s/loom_and_database_drivers/

**Comment by hantsy** [comment]
Spring WebFlux existed for over 5 years. 

We choose Spring WebFlux and Kotlin Coroutines in the new backend project, and use R2dbc for db operations(Spring do not support other reactive solutions now). 

Quarkus also embrace reactive in the new Quarkus 3.x it will be primary solution in the future, benefit from Hibernate project, Quarkus supports Hibernate Reactive, but it is based on another reactive drivers instead of JDBC.

Micronaut supports both R2dbc and Hibernate Reactive(and the built-in reactive drivers for simple sql operations).

We can not reject reactive streams spec nowadays.

https://www.reactive-streams.org/

**Comment by rdehuyss** [comment]
Thanks for that info but I don't understand what you mean with it 😊 . 

As my time is limited, I will not be adding support for R2DBC. Can I understand that you will be adding support for it in JobRunr? Or is your company willing to pay for the development of this feature?

**Comment by hantsy** [comment]
Now we are using a custom solution for the scheduled tasks, not depends on any job scheduling framework/libs.

**Comment by ghahramani** [comment]
IMHO, it's important for this outstanding library to support reactive libraries. Kotlin has had a feature (coroutines) similar to the virtual threads (Project Loom) since its first release but still not everyone has adopted coroutines. Moreover, there are still hundreds of thousands of projects relying on Webflux, RxJava, and RxKotlin. Many of these technologies are in active use within our company, and using a blocking datasource can lead to significant issues in reactive projects. I think supporting Reactive can increase the usage of these libraries and can lead to even better sales for Jobrunr Pro.

At present, I am in the process of developing a microservice that employs Jobrunr in a non-reactive fashion. This microservice acts as an external scheduler, enabling the execution of specific endpoints in reactive microservices at scheduled intervals.
