### ISSUE TITLE
[BUG] Spring boot health actuator integration

### ISSUE THREAD

**Issue by stinuz** [jobrunr/jobrunr#270]
The health actuator endpoint implementation only looks at the JobRunrProperties but the health check always fails when you configure the backgroundServer using the fluent api. 

(Note that the example in the readme is out of date with the current version because now the JobRunr.configure().initialize() will return a JobRunrConfigurationResult instead of the JobScheduler.

**Comment by rdehuyss** [comment]
Open for a PR for this.

**Comment by rdehuyss** [comment]
Actually, I've given this a second thought. The actuators are only available if you use the spring-boot-starter. 

By design, the core is agnostic to frameworks as it supports spring, quarkus and micronaut.

The actuators are also only mentioned inside the Spring documentation, not on the fluent api page. You can create all the beans yourself if you don't want to use the spring-boot-starter. See https://github.com/jobrunr/jobrunr/tree/master/framework-support/jobrunr-spring-boot-starter/src/main/java/org/jobrunr/spring/autoconfigure/metrics and https://github.com/jobrunr/jobrunr/tree/master/framework-support/jobrunr-spring-boot-starter/src/main/java/org/jobrunr/spring/autoconfigure/health.
