### ISSUE TITLE
[BUG] Metadata always empty for getJobById

### ISSUE THREAD

**Issue by daniel-huser** [jobrunr/jobrunr#355]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
When loading a Job via jobStorageProvider.getJobById the metadata Map is always empty.
This is in my opinion due to the deepClone and the metadata map being initialized in the constructor.

**Environment**
I'm using JobRunr version: 4.0.8
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): OpenJDK 1.8.0_292
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): SAP HANA (DB2 as Dialect)

**How to Reproduce**
Store Metadata in job (on the DB the values are properly set in the JSON Column)
jobContext.saveMetadataIfAbsent("user", user);
---
org.jobrunr.jobs.Job job = jobStorageProvider.getJobById(jobId);

**Expected behavior**
The Metadata which was saved, being returned.

Thanks for any help :)

**Comment by rdehuyss** [comment]
No worries - feel free to star the repo if you're enjoying JobRunr!

**Comment by patkujawa-wf** [comment]
This might be a bit off-topic, but I was surprised by this statement:

> Note that in JobRunr 5 the context will probably be cleared after the job succeeded for storage size reasons. The context is more meant for storing state between job executions of the same job (i.e. if you have a large job that exists out of multiple steps, you can save which steps succeeded so that in case of a failure and the job is retried, you can already skip the succeeded steps).

We are using jobrunr in an async API where users can start a job and then poll for its progress (and end result), and we're using metadata to store that end result. Since users may end up polling a bit after a job has succeeded, I'm concerned to hear that metadata would be deleted (right) after success.

Is there another recommendation for where to store metadata for after a job has completed (e.g. for a day at least)? One obvious answer is, "somewhere else in your database," but I wasn't sure if jobrunr had another mechanism :)

Thanks!
