### ISSUE TITLE
[Feature] Allow to update/replace jobs

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#363]
**Is your feature request related to a problem? Please describe.**
Updating existing jobs is currently not possible.

**Describe the solution you'd like**
I want to be able to replace jobs based on a given id - no matter what state they are in.

**Describe alternatives you've considered**
Deleting and recreating but that's performance wise not ideal

**Additional context**
See Github issue #236

**Comment by JanHolger** [comment]
We have jobs that have a certain preconditions and using the batching/chaining functionality would kind of work but block the entire queue while checking and waiting for preconditions to be met. Having a way to reschedule a job at a later date would be great for such applications. Currently this is only possible by scheduling a new job in the existing one.

An ability to set the remaining retries would also be great to allow the job to decide on the fatality of errors. Some errors might make a job unprocessable but JobRunr will still try to execute them several times unless you return instead of throwing an Exception but this would mark it as successful while it wasn't.

**Comment by rdehuyss** [comment]
Fixed in JobRunr Pro v5.0.0
