### ISSUE TITLE
[Feature] Support for smaller polling intervals for Redis

### ISSUE THREAD

**Issue by JanHolger** [jobrunr/jobrunr#366]
**Is your feature request related to a problem? Please describe.**
Currently (i think since version 4) the minimum polling interval is 5 seconds which is incredibly slow and makes JobRunr unusable for many applications.

**Describe the solution you'd like**
Allow smaller polling intervals depending on the storage implementation used.

**Describe alternatives you've considered**
There is no real alternative with JobRunr. The only alternative is to not use JobRunr for tasks that need to be processed asap.

**Comment by rdehuyss** [comment]
Redis is currently already the database with which I / JobRunr have the most troubles as soon as there is some load (some keys within a transaction are not saved under load, I did not find the root cause yet. See #352 & #232). The support issues I have related to Redis take up too much of my personal time.

Issue #88 will hopefully be implemented in JobRunr Pro 5 and provide a solution for this.

I hope you understand the reasoning why I won't change the poll interval for any storage provider.

**Comment by hemju** [comment]
I want to reopen this issue. I don't think the intervals should be lowered only for Redis, they should be lowered for all storage providers. Any database can handle calls in under 1 second, so shouldn't it be up to the developer to set the polling intervals?  In Quartz for example it is not a problem to have an interval of 1 second.

Is there any specific reason why the minimum interval is 5 seconds?

**Comment by rdehuyss** [comment]
Yes - the amount of calls that happen (it's actually quite a lot) and the issues that arise when lowering this. 

What is the business case to reduce this?

**Comment by hemju** [comment]
> Yes - the amount of calls that happen (it's actually quite a lot) and the issues that arise when lowering this.

Could you please let me know which issues these are? Maybe these issues are the developers/callers' responsibility, not the one from Jobrunr.

Further, I see this issue: https://github.com/jobrunr/jobrunr/issues/88 Does that mean the issues on jobrunner's end are resolved?

Btw. from a behavior's point of view. If a scheduled job takes longer than the interval, there are a couple of options:

* Skip the new execution.
* Fill up a queue.
* Throw an exception

I think that with Skip most of the use cases are handled.

> What is the business case to reduce this?

We have a couple of services that are regularly checking some database tables and based on that start the execution of a job. So basically a polling background job schedules other background jobs. We need to do this in a background job since the scheduling of the new jobs depends on certain conditions. This is a time-sensitive operation, so we have an interval of 1 second to check.

**Comment by rdehuyss** [comment]
Well - all of your needs are probably covered with JobRunr Pro where instant job scheduling is possible (the fix for #88) without extra load on the database.

Real-time scheduling is coming in Q3 in JobRunr Pro.

**Comment by hemju** [comment]
> Well - all of your needs are probably covered with JobRunr Pro where instant job scheduling is possible (the fix for https://github.com/jobrunr/jobrunr/issues/88) without extra load on the database.

No, that is not possible. Since we have to make sure that one resource (e.g. project) only one background can run. So we definitely need a smaller interval to achieve that.

> Real-time scheduling is coming in Q3 in JobRunr Pro.

Please note, we haven't talked about scheduling, I am interested in the polling interval for recurring jobs.

We are definitely interested in Jobrunr since Quartz is just not dev friendly. I am happy to pay for Pro if it allows us to be more productive. Please note that we are still a small company. I just had a look at the pricing: 

> Eligible if up to 5 employees.

Does this mean *all* employees or just technical employees (developers)? Since the developers are the only ones working with it.
