### ISSUE TITLE
[Enhancement] InvalidCronExpressionException: also allow 7 as day_of_week field

### ISSUE THREAD

**Issue by jloisel** [jobrunr/jobrunr#520]
```java
InvalidCronExpressionException: invalid day_of_week field: "7". maximum allowed value for day_of_week field is "6" 
```

Most schedulers (like Quartz) support 0-7 as day of week, where 0 = 7 = sunday. It causes compatiblity issues to have only 0-6 day of week when migrating from Quartz to Jobrunr.

**Comment by rdehuyss** [comment]
I've considered it but I don't necessarily want JobRunr to be compatible with Quartz.

The official standard is 0-6 and that's what JobRunr supports. If Quartz decided to do things different than the official standard that's their choice but as I want to keep JobRunr lean & mean this also means not adding in hacks because predecessors decided to do so.

On top of that - the fix when moving to JobRunr is easy 😊 .

**Comment by jloisel** [comment]
Supporting a wider range of syntax would make it easier to adopt jobrunr when already running an alternate system.
