### ISSUE TITLE
[BUG] Recurring Jobs goes to Idle state after some time

### ISSUE THREAD

**Issue by Kumar-Somesh** [jobrunr/jobrunr#698]
### JobRunr Version

5.1.4

### JDK Version

Open JDK 11

### Your SQL / NoSQL database

MS SQL Server

### What happened?

We have implemented two services using JobRunr and Spring. Both of these services are recurring services and self contained services means each of them are running on different port with background server enabled in both of them, also the services are using different tables in MS SQL. Right now we have set the interval as 2 minutes for both the services.

The issue we are facing is that after some time, the recurring job stop executing even after the server is up and running. Somehow it goes to idle state.

### How to reproduce?

@Recurring(id = "cpa-file-transfer-service", cron = "*/2 * * * *")
@Job(name="CPA File Transfer Service")
public void recurringJob(JobContext jobContext) {
   //service method called here
}

**Comment by rdehuyss** [comment]
Hi @Kumar-Somesh , since you are not running the latest JobRunr OSS version, I'm afraid I can't give you any support as it takes too much of my personal time. If you do want to receive support you will need to update to the latest JobRunr version or take a support contract. 

Also, there is no idle state in JobRunr. What can happen is:
- JobRunr stops processing due to [network issues with the database](https://www.jobrunr.io/en/documentation/pro/database-fault-tolerance/)
- that not all Recurring Jobs get processed due to [DB performance](https://www.jobrunr.io/en/documentation/background-methods/recurring-jobs/).

Note that with some customers JobRunr is running 1500 recurring jobs every couple of minutes so I'm quite sure this is related to your setup.

**Comment by Kumar-Somesh** [comment]
Thank you I will update to latest version.
