### ISSUE TITLE
[Question] Are we missing a state? CANCELED?

### ISSUE THREAD

**Issue by oazais** [jobrunr/jobrunr#71]
Hello,
I'm surprised with the following result.
When I want to delete a Job in Processing state, the action is well executed and the BackGroundJobServer stop the process.
But when I'm looking at the job history, the last state of the Job move to Succeeded even though it has been stopped.
Then, how can I easily know what are the Jobs that have been deleted during process?
May be adding a new state CANCELED will be useful.
What do you think?
```json
"jobHistory": [{
            "@class": "org.jobrunr.jobs.states.EnqueuedState",
            "state": "ENQUEUED",
            "createdAt": "2020-11-24T07:55:15.270824Z"
        }, {
            "@class": "org.jobrunr.jobs.states.ProcessingState",
            "state": "PROCESSING",
            "createdAt": "2020-11-24T07:55:24.045138Z",
            "serverId": "a59017cf-4f8a-4e6d-b041-345f3ef512c3",
            "updatedAt": "2020-11-24T07:55:53.989664300Z"
        }, {
            "@class": "org.jobrunr.jobs.states.DeletedState",
            "state": "DELETED",
            "createdAt": "2020-11-24T07:55:54.003666600Z"
        }, {
            "@class": "org.jobrunr.jobs.states.SucceededState",
            "state": "SUCCEEDED",
            "createdAt": "2020-11-24T07:55:54.004667900Z",
            "latencyDuration": 38.732842600,
            "processDuration": 0.001001300
        }
    ],
```

**Comment by rdehuyss** [comment]
Hi,

The reason you are seeing this is because of the fact that multiple things happen at the same time...

- you indeed deleted the job (and have instant feedback about it in the UI - perhaps that is the problem)
- but as JobRunr only checks every 15 seconds whether a job is deleted, your job did run until the end and thus finished successfully.

If you would have a job that takes 10 minutes and you deleted is after 5 minutes, you would not have seen the last `SUCCES` state.

I can see the the value of having a cancelled state but I think it is still the same as deleted in the end.

An option could be that we have a reason in the deleted state specifying why it was deleted. These reasons could be:
- JobRunr maintenance - deleting succeeded job
- Job deleted via API
- Job deleted via dashboard

For the moment, I'm hesitant to add the `CANCELLED` state as it adds a lot of extra complexity (what are the allowed state changes, ... ) and I don't know if it will add a lot of extra value.

**Comment by oazais** [comment]
Thanks for your answer, I understand better now.
