### ISSUE TITLE
[BUG] could not find class PloymorphicTypeValidator when there are gson and jackson(<=2.9.0) both in classpath

### ISSUE THREAD

**Issue by dongxuwang** [jobrunr/jobrunr#745]
### JobRunr Version

6.1.3

### JDK Version

OpenJDK 1.8.0_292

### Your SQL / NoSQL database

InMemory

### What happened?

We have a old project need to use jobrunr as job engine. While we also have gson and jackson 2.9.0 in the project. Because jobrunr would collect jackson first, the exception would be thrown.

### How to reproduce?

Use both gson and jackson (<=2.9.0) within project. Then run any examples for jobrunr.

**Comment by rdehuyss** [comment]
I'm afraid that JobRunr does not support Jackson <= 2.9.0 (it only has 66 vulnerabilities 🤣 and is over 6 years old).

If you have a look at the open-source code, you will see that you can configure it to use the JsonMapper that you want.

**Comment by dongxuwang** [comment]
> use the JsonMapper that you want.

Hey @rdehuyss , thank you for the reply. But you'll still get the exception even you config that JsonMapper.

**Comment by rdehuyss** [comment]
Hi @dongxuwang - well, I'm sure that JobRunr works (because of all the integration tests) and the fact that a lot of people use it daily.

So, I don't really know what you expect from my side? I noticed you work for Apache - I hope you understand that community support is limited but if you think I can help with something, then please let me know or [schedule a call in my agenda](https://calendar.app.google/kZHCSy4t35raCEbB7).
