### ISSUE TITLE
[BUG] JobRunr crashes when some other job is deleted while `auto-commit` was set to `false`

### ISSUE THREAD

**Issue by tan9** [jobrunr/jobrunr#748]
### JobRunr Version

6.1.3

### JDK Version

OpenJDK 17

### Your SQL / NoSQL database

PostgreSQL

### What happened?

For applications generated by JHipster, the [HikariCP `auto-commit` was set to `false`](https://github.com/jhipster/jhipster-sample-app/blob/v7.9.3/src/main/resources/config/application-prod.yml#L41). And HikariCP is also the [default connection pool of Spring Boot](https://github.com/spring-projects/spring-boot/blob/v3.0.6/spring-boot-project/spring-boot-starters/spring-boot-starter-jdbc/build.gradle#L9).

We found a weird situation in the above setup. If there are two jobs running, say `job1` and `job2`. Once the user deletes `job1`, JobRunr will start to dump `ConcurrentJobModificationException` while processing `job2` and then shutting it down after 5 errors! 

And if we set `auto-commit=true`, JobRunr will run as expected.

### How to reproduce?

See https://github.com/tan9/jobrunr-autocommit-issue-poc

**Comment by mashurex** [comment]
We've been dealing with this for a while now as well (RDS Postgres) but I did find something interesting. I wasn't able to get @tan9's POC to fire any ConcurrentJobModificationExceptions locally, even with default Spring configured HikariCP DataSource bean. 

However, when deployed to our development cloud environment we were still getting the exceptions (although MUCH less than we had been), even with a custom configuration that created a brand new HikariCP DataSource just for JobRunr that had `isAutoCommit=true`.  

- We use PGPool in front of our RDS instances and our cluster uses multi-region replication. 
- PGPool sends writes to the primary region and directs reads the secondary/read-only region. 
- There can be as much as a 250ms replication lag (though in our testing it is more like 20ms).

It is my belief, that at least for us, we're getting the exceptions due to replication lag. I bring this up to suggest it may be worth looking at any transaction lock wait times, performance metrics, etc. in database instances, as that could be a culprit.

For us, we're going to use a Redis storage provider to get around the issue.

**Comment by rdehuyss** [comment]
@mashurex currently, I do not recommend the RedisStorageProvider.

Instead, I recommend that JobRunr writes and reads from the same DB.

**Comment by rdehuyss** [comment]
I think I have an idea of the root cause for the issue by @tan9 . Still need to verify it in a reproducible intégration test.

**Comment by rdehuyss** [comment]
Root cause has been identified. Still need to think a way of fixing it without too much impact.
