### ISSUE TITLE
[BUG] @job annotation is not registering jobfilters after upgrade to spring boot 3.1.2 and jobrunr 6.3.0

### ISSUE THREAD

**Issue by seniordanel** [jobrunr/jobrunr#829]
### JobRunr Version

6.3.0

### JDK Version

17

### Your SQL / NoSQL database

mongodb

### What happened?

We are upgrading from spring boot 2.74 to spring boot 3.1.2 and with that we upgraded to jobrunr 6.3.0, to have the latest version.

for some reason the job filters stopped working and the retries is defaulted to 10, even if everything is registered in the @Job annotation (nothing is trouched, it worked great before the upgrade) We also tried to use jobrunr fluent api to register the retries and the jobfilter, which failed to work.

### How to reproduce?

execute job using BackgroundJob.enqueue(jobLambda) and annotatee the lamda with

 

@Job(name = "name (id: %0)", retries = 0, jobFilters = {implementationClientFilter.class,
           ImplementationJobServerFilter.class})

 

in the implementation of client filter i am implementing the onCreating method and in the implementation of server filter i am implementing the onprocessing method. what i am doing is passing the user credentials from the client to the server for the job.

 

I can see that the logic in the implemented methods are not being executed.

 

I also tried using the fluent api of jobrunr as a bean like this, which also didn't work:

@Bean
    @RefreshScope
    public JobRunrConfiguration.JobRunrConfigurationResult jobRunrConfigurationResult(
            MongoDBStorageProvider mongoDBStorageProvider) {
        return JobRunr.configure()
                .useStorageProvider(mongoDBStorageProvider)
                .withJobFilter(
                        new implementationJobServerFilter(),
                        new implementationJobClientFilter(),
                        new RetryFilter(0))
                .initialize();

    }

 

how do i register the filters?

**Comment by rdehuyss** [comment]
Hi @seniordanel , thanks to upgrading to JobRunr v6.3 but if I recall correctly, I asked for a github repo that reproduces the issue.

Although I was 99% sure that this was not an issue in JobRunr, now I had to work on a Sunday to try to reproduce your issue - which I can't. The code you are talking about has test coverage of over 90% and the test that I now added shows that it works.

If you want me to look into this, please setup a simple github repo that reproduces the issue. 

Opensource software development is not a lot of fun. I ask everyone using the dashboard to star the repo when they enjoy using JobRunr. Since you upgraded, I assume you're using JobRunr already a long time yet you did not star the repo, which is quite a simple thing to do and a small token of appreciation. And then you ask for support without following the community guidelines (you don't mention where you work on your Github profile) and without creating a repo that reproduces the issue, which just makes me almost angry.

Your next issue will be closed immediately without any response if you don't complete your github profile like we ask in the community guidelines.

**Comment by rdehuyss** [comment]
Sorry for my rant earlier on but I really try to keep open issues low. 

If then issues are created without any of the info I ask, it's difficult and causes a lot of stress. I hope you understand.

**Comment by danelsenior** [comment]
I couldn't replicate the problem in a fresh project. However, I encountered an issue related to the reflection mechanism in Spring. In Spring 2.7.4, while using the `JobUtils#getJobAnnotation` method, the `jobDetails` class name is `com.citi.halo.issues.batch.create.BatchIssuesCreateLogic`. But in Spring 3.1.2, using the same method, the class name changes to `com.citi.halo.issues.batch.create.BatchIssuesCreateLogic$$SpringCGLIB$$0`. I suspect that Spring is wrapping the class with a CGLIB proxy, which might be causing the reflection to fail. Do you have any insights into what might be going wrong?


<img width="511" alt="image" src="https://github.com/jobrunr/jobrunr/assets/63645331/932e295a-53a4-465e-ac49-3d9c4aa1647c">
<img width="438" alt="image" src="https://github.com/jobrunr/jobrunr/assets/63645331/22316729-128d-43fb-94ba-e7643edf915b">

**Comment by rdehuyss** [comment]
If you can create a Github issue that reproduces it, I can look into it. But without it, setting things up to reproduce things takes a loooooot of my personal time.

**Comment by seniordanel** [comment]
6.3.1 looks promising 😊 any idea when its going to available in the repositories?

**Comment by rdehuyss** [comment]
I published it this morning to maven central and from what I can see, it should be available.

See https://central.sonatype.com/artifact/org.jobrunr/jobrunr/versions

**Comment by rdehuyss** [comment]
@seniordanel - did JobRunr 6.3.1 your issue?

**Comment by seniordanel** [comment]
yes it did, thank you 🙏
