### ISSUE TITLE
[BUG/IMPROVEMENT] Oracle 11g is not supported

### ISSUE THREAD

**Issue by nlescure-pictet** [jobrunr/jobrunr#85]
According to the code, org.jobrunr.storage.sql.common.db.dialect.OracleDialect#limitAndOffset, the query syntax: 
`OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY`
 is not supported by oracle 11g.
I get the error:
`ORA-00933: SQL command not properly ended`

Suggestion: it would be nice to be able to provide its own org.jobrunr.storage.sql.common.db.dialect.Dialect to use so that if someone needs to support a tier database (which might not be supported yet), he can easily do it.

Thanks for the great work anyway !!

**Comment by rdehuyss** [comment]
Indeed, I'm afraid Oracle 11g is not supported - it was a tough decision to make but it's over 11 years old and extended support was ended on 12/31/2020.

I try to keep JobRunr up-to-date dependency wise and I thought it was not so easy to make pagination in Oracle 11g (as it does not support `offset` and `fetch next` syntax.

Do you know of a way to add pagination for Oracle 11g which can easily be added **at the end of an SQL query clause** (otherwise a lot of refactoring is needed)? If so, I'm happy to add an Oracle 11 g dialect.

**Comment by nlescure-pictet** [comment]
Thanks for the quick answer.
Yes, I agree with you and I think I'll push for a DB migration instead :)

Cheers,
