### ISSUE TITLE
[Improvement] Logs management is a great feature however ...

### ISSUE THREAD

**Issue by nlescure-pictet** [jobrunr/jobrunr#86]
Hi,

I quite like the idea of being able to gather the batch execution logs. Thanks for the feature :+1: 
However, I am afraid the current implementation doesn't scale very well if a batch starts producing too many logs.
I see that logs are stored in the database via a single JSON representation of the job (status, logs, etc...). Therefore, when loading the job execution later on, we fetch the whole bunch of logs associated with the job execution in one go. I can see that the dashboard struggles loading such "big" job executions as well. I can even observe out of memory errors in some cases.

Solution:
I would suggest to use a job_logs table associated with a pagination or an endless scrolling feature on the dashboard side to be able to handle such big executions.

Obviously I could reduce the jobs verbosity and/or increase the jobrunr app Xmx but still, I recon there is some room for improvement here.

Again, thanks for the great work.

**Comment by rdehuyss** [comment]
Hi,

I've considered your valuable input but I don't know if I agree - for me, the logging feature in JobRunr allows you to quickly see how jobs are doing, where exactly a job is in its lifecycle or to see why a Job failed (with stack trace off course).

Adding `debug`- kind of logging does not feel right for me, because it will impact performance (extra writes to a database probably already under load because of a lot of jobs). There are also other great tools to visualize logging (think ELK stack).

It's also explicitly mentioned on the website where it says debug logging is not supported: https://www.jobrunr.io/en/documentation/background-methods/logging-progress/.

I hope you understand my point of view.
