### ISSUE TITLE
[Feature] separate pollIntervalInSeconds configuration for polling task and zookeeping

### ISSUE THREAD

**Issue by HashZhang** [jobrunr/jobrunr#933]
the pollIntervalInSeconds  of configuration mainly affect two tasks:
 - serverZookeeper: for server master zookeeping
 - jobZookeeper: for job schedule

  the default polling interval is 15s, which is suitable for serverZookeeper, but maybe too long for jobZookeeper.
  If we shorten the polling interval to 1s (currently not available, min is 5s), it would be suitable for jobZookeeper but not suitable for serverZookeeper.
  
  Therefore, I think it would be better if there would be a 'pollIntervalInSeconds' for jobZookeeper and another 'pollIntervalInSeconds' for serverZookeeper.

**Comment by HashZhang** [comment]
And I also have recognized that there is pending PR related to separate maintenance tasks (delete deleted jobs, history, etc.) from jobZookeeper, which is also a highly required promotion.

**Comment by rdehuyss** [comment]
The only reason for a smaller pollIntervalInSeconds is faster processing. 

In the Pro version, instant processing is available and solved in a different way (so almost no enqueued time).

As an opensource developer of a project that some call feature complete, I prefer to have some leverage to make developers and companies switch to the Pro version.

Otherwise, I would have burned out a long ago and this project would not be maintained anymore.

See https://github.com/jobrunr/jobrunr/discussions/769 for more info.
